package database

// TODO: Load this from the files at the src/suspects.
var defaultSuspects = []Suspect{
	{Image: "1.jpg"},
	{Image: "2.jpg"},
	{Image: "3.jpg"},
	{Image: "4.jpg"},
	{Image: "5.jpg"},
	{Image: "6.jpg"},
	{Image: "7.jpg"},
	{Image: "8.jpg"},
	{Image: "9.jpg"},
	{Image: "10.jpg"},
	{Image: "11.jpg"},
	{Image: "12.jpg"},
	{Image: "13.jpg"},
	{Image: "14.jpg"},
	{Image: "15.jpg"},
	{Image: "16.jpg"},
	{Image: "17.jpg"},
	{Image: "18.jpg"},
	{Image: "19.jpg"},
	{Image: "20.jpg"},
	{Image: "21.jpg"},
	{Image: "22.jpg"},
	{Image: "23.jpg"},
	{Image: "24.jpg"},
	{Image: "25.jpg"},
	{Image: "26.jpg"},
	{Image: "27.jpg"},
	{Image: "28.jpg"},
	{Image: "29.jpg"},
	{Image: "30.jpg"},
}

var defaultQuestions = []Question{
	{
		English: "Does the suspect like pizza?",
		Czech:   "Má podezřelý rád pizzu?",
		Polish:  "Czy podejrzany lubi pizzę?",
		Topic:   "basic",
		Level:   1,
	},
	{
		English: "Is the suspect leftist?",
		Czech:   "Je podezřelý levičák?",
		Polish:  "Czy podejrzany jest lewicowy?",
		Topic:   "political",
		Level:   1,
	},
	{
		English: "Does the suspect have depressions?",
		Czech:   "Má podezřelý deprese?",
		Polish:  "Czy podejrzany ma depresje?",
		Topic:   "psychological",
		Level:   1,
	},
	{
		English: "Is the suspect a fan of social media?",
		Czech:   "Je podezřelý fanouškem sociálních sítí?",
		Polish:  "Czy podejrzany jest fanem mediów społecznościowych?",
		Topic:   "sociological",
		Level:   1,
	},
	{
		English: "Does the suspect enjoy traveling?",
		Czech:   "Má podezřelý rád cestování?",
		Polish:  "Czy podejrzany lubi podróże?",
		Topic:   "basic",
		Level:   1,
	},
}

/*
	{English: "Is the suspect environmentally conscious?", Topic: "political", Level: 1},
	{English: "Does the suspect attend therapy?", Topic: "psychological", Level: 1},
	{English: "Does the suspect believe in traditional family values?", Topic: "sociological", Level: 1},
	{Text: "Is the suspect vegetarian?", Topic: "basic", Level: 1},
	{Text: "Does the suspect vote regularly?", Topic: "political", Level: 1},
	{Text: "Does the suspect struggle with anxiety?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect an extrovert?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy sports?", Topic: "basic", Level: 1},
	{Text: "Does the suspect have strong political opinions?", Topic: "political", Level: 1},
	{Text: "Does the suspect meditate?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect part of a close-knit community?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy cooking?", Topic: "basic", Level: 1},
	{Text: "Is the suspect involved in activism?", Topic: "political", Level: 1},
	{Text: "Does the suspect have mood swings?", Topic: "psychological", Level: 1},
	{Text: "Does the suspect follow trends?", Topic: "sociological", Level: 1},
	{Text: "Is the suspect a fan of sci-fi movies?", Topic: "basic", Level: 1},
	{Text: "Does the suspect lean towards conservatism?", Topic: "political", Level: 1},
	{Text: "Does the suspect practice mindfulness?", Topic: "psychological", Level: 1},
	{Text: "Does the suspect enjoy large social gatherings?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy hiking?", Topic: "basic", Level: 1},
	{Text: "Does the suspect have progressive views?", Topic: "political", Level: 1},
	{Text: "Does the suspect suffer from insomnia?", Topic: "psychological", Level: 1},
	{Text: "Does the suspect belong to a minority group?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy reading books?", Topic: "basic", Level: 1},
	{Text: "Is the suspect politically active online?", Topic: "political", Level: 1},
	{Text: "Does the suspect have low self-esteem?", Topic: "psychological", Level: 1},
	{Text: "Does the suspect belong to a religious organization?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect prefer tea over coffee?", Topic: "basic", Level: 1},
	{Text: "Does the suspect discuss politics frequently?", Topic: "political", Level: 1},
	{Text: "Does the suspect have a phobia?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect involved in charity work?", Topic: "sociological", Level: 1},
	{Text: "Is the suspect a pet owner?", Topic: "basic", Level: 1},
	{Text: "Does the suspect believe in free healthcare?", Topic: "political", Level: 1},
	{Text: "Does the suspect experience panic attacks?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect active in a subculture?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy classical music?", Topic: "basic", Level: 1},
	{Text: "Does the suspect support the current government?", Topic: "political", Level: 1},
	{Text: "Does the suspect practice positive affirmations?", Topic: "psychological", Level: 1},
	{Text: "Does the suspect have many friends?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy fast food?", Topic: "basic", Level: 1},
	{Text: "Does the suspect support LGBTQ+ rights?", Topic: "political", Level: 1},
	{Text: "Does the suspect struggle with stress?", Topic: "psychological", Level: 1},
	{Text: "Does the suspect belong to a sports team?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect watch reality TV?", Topic: "basic", Level: 1},
	{Text: "Does the suspect believe in socialism?", Topic: "political", Level: 1},
	{Text: "Does the suspect engage in self-care?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect socially awkward?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy board games?", Topic: "basic", Level: 1},
	{Text: "Does the suspect align with feminist ideals?", Topic: "political", Level: 1},
	{Text: "Does the suspect have trust issues?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect active in online forums?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect drink alcohol?", Topic: "basic", Level: 1},
	{Text: "Does the suspect follow a specific political leader?", Topic: "political", Level: 1},
	{Text: "Does the suspect have anger issues?", Topic: "psychological", Level: 1},
	{Text: "Does the suspect regularly attend social events?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy gardening?", Topic: "basic", Level: 1},
	{Text: "Does the suspect discuss current events frequently?", Topic: "political", Level: 1},
	{Text: "Does the suspect have a fear of failure?", Topic: "psychological", Level: 1},
	{Text: "Does the suspect have a strong social network?", Topic: "sociological", Level: 1},
	{Text: "Is the suspect a fan of horror movies?", Topic: "basic", Level: 1},
	{Text: "Does the suspect believe in capitalism?", Topic: "political", Level: 1},
	{Text: "Does the suspect practice emotional regulation?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect involved in local politics?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy fine dining?", Topic: "basic", Level: 1},
	{Text: "Does the suspect support authoritarianism?", Topic: "political", Level: 1},
	{Text: "Does the suspect feel isolated?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect part of a youth group?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect collect anything?", Topic: "basic", Level: 1},
	{Text: "Does the suspect support progressive taxation?", Topic: "political", Level: 1},
	{Text: "Does the suspect struggle with self-doubt?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect involved in community outreach?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect enjoy outdoor activities?", Topic: "basic", Level: 1},
	{Text: "Does the suspect support universal basic income?", Topic: "political", Level: 1},
	{Text: "Does the suspect deal with imposter syndrome?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect well-connected in their neighborhood?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect prefer cats over dogs?", Topic: "basic", Level: 1},
	{Text: "Does the suspect believe in free speech absolutism?", Topic: "political", Level: 1},
	{Text: "Does the suspect regularly journal?", Topic: "psychological", Level: 1},
	{Text: "Is the suspect engaged in social justice movements?", Topic: "sociological", Level: 1},
	{Text: "Does the suspect have tattoos?", Topic: "basic", Level: 1},
	{Text: "Does the suspect advocate for stricter gun laws?", Topic: "political", Level: 1},
}
*/
