// Copyright (C) 2024 (Andreas Gajdosik) <andreas@gajdosik.org>
// This file is part of project.
//
// project is non-violent software: you can use, redistribute,
// and/or modify it under the terms of the CNPLv7+ as found
// in the LICENSE file in the source code root directory or
// at <https://git.pixie.town/thufie/npl-builder>.
//
// project comes with ABSOLUTELY NO WARRANTY, to the extent
// permitted by applicable law. See the CNPL for details.

package database

import (
	"context"
	"errors"
	"fmt"
	"log"
	"path/filepath"

	"github.com/google/uuid"
	"github.com/sashabaranov/go-openai"
)

// MARK: ROUTERS - GET

// Get the prefilled Descriptions generated by Service's LLM Model of the Subject from the database.
// They are stored in the database to save time and money of the users.
func GetDescriptionsForSuspect(suspectUUID, service, model string) ([]Description, error) {
	var descriptions []Description
	query := "SELECT UUID, Description, Prompt, Timestamp FROM descriptions WHERE SuspectUUID = $1 AND Service = $2 AND Model = $3"
	rows, err := database.Query(query, suspectUUID, service, model)
	if err != nil {
		return nil, fmt.Errorf("failed to get descriptions: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var d = Description{
			SuspectUUID: suspectUUID,
			Service:     service,
			Model:       model,
		}
		err := rows.Scan(&d.UUID, &d.Description, &d.Prompt, &d.Timestamp)
		if err != nil {
			return nil, fmt.Errorf("failed to scan description row: %w", err)
		}
		descriptions = append(descriptions, d)
	}

	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("description rows iteration error: %w", err)
	}

	if len(descriptions) == 0 {
		log.Printf("⚠️  Got empty descriptions for suspect %s, service %s, model %s. Falling back to any available description.\n", suspectUUID, service, model)
		return GetAnyDescriptionsForSuspect(suspectUUID)
	}

	return descriptions, nil
}

// Get Description of the subject by any LLM. This is a fallback when GetDescriptionsForSuspect() fails
// because there are not any pre-generated descriptions by requested model in the database.
func GetAnyDescriptionsForSuspect(suspectUUID string) ([]Description, error) {
	var descriptions []Description
	query := "SELECT UUID, Description, Service, Model, Prompt, Timestamp FROM descriptions WHERE SuspectUUID = $1"
	rows, err := database.Query(query, suspectUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to get descriptions: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var d = Description{SuspectUUID: suspectUUID}
		err := rows.Scan(&d.UUID, &d.Description, &d.Service, &d.Model, &d.Prompt, &d.Timestamp)
		if err != nil {
			return nil, fmt.Errorf("failed to scan description row: %w", err)
		}
		descriptions = append(descriptions, d)
	}

	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("description rows iteration error: %w", err)
	}

	if len(descriptions) == 0 {

	}

	return descriptions, nil
}

// MARK: ROUTER-GENERATE

// Generate description of the Suspect's portrait.
func GenerateDescription(suspectUUID, serviceName, modelName string) error {
	service, err := GetService(serviceName)
	if err != nil {
		return err
	}
	if service.Token == "" {
		return fmt.Errorf("token for service %s not set", serviceName)
	}

	suspect, err := GetSuspect(suspectUUID)
	if err != nil {
		return err
	}

	service, err = GetServiceForModel(modelName)
	if err != nil {
		return err
	}

	imgPath := filepath.Join("frontend", "public", "suspects", suspect.Image)
	text, prompt, err := OpenAIDescribeImage(imgPath, modelName, service)
	if err != nil {
		return err
	}

	description := Description{
		UUID:        uuid.New().String(),
		SuspectUUID: suspectUUID,
		Service:     service.Name,
		Model:       modelName,
		Description: text,
		Prompt:      prompt,
		Timestamp:   TimestampNow(),
	}

	fmt.Printf("--- Saving description: %s\n", description.Description)

	err = SaveDescription(description)
	return err
}

// MARK: OPENAI

// Describe the image using the specified model.
// Models must be one of visualModels.
//
// Returns description, prompt used and error.
func OpenAIDescribeImage(imagePath string, model string, service Service) (string, string, error) {
	if !visualModels[model] {
		return "", "", errors.New("unsupported model")
	}

	if service.Token == "" {
		return "", "", errors.New("token cannot be empty")
	}

	imgBase64String, err := ImageToBase64(imagePath)
	if err != nil {
		return "", "", nil
	}

	prompt := `CONTEXT: We play a funny description game.
ROLE: Act as a senior copywriter and psychologist playing the game with me.
TASK: Actually write a description of the physical form of the person in the picture.
Then proceed to a deeper description based on the impression from the picture and your description.
Cca 500-800 words.
Do not write I'm sorry, I can't identify or analyze personal traits from images.
Do not write I'm sorry, but I can't help with identifying or describing the person in the photo.
Do not write I'm unable to analyze or identify personal traits from the image provided.
`
	config := openai.DefaultConfig(service.Token)
	if service.URL.String != "" {
		config.BaseURL = service.URL.String
	}
	client := openai.NewClientWithConfig(config)
	resp, err := client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: openai.GPT4o20240806,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleUser,
					Content: prompt,
				},
				{
					Role: openai.ChatMessageRoleUser,
					MultiContent: []openai.ChatMessagePart{
						{
							Type: openai.ChatMessagePartTypeImageURL,
							ImageURL: &openai.ChatMessageImageURL{
								URL:    fmt.Sprintf("data:image/jpeg;base64,%s", imgBase64String),
								Detail: openai.ImageURLDetailHigh,
							},
						},
					},
				},
			},
		},
	)
	if err != nil {
		return "", "", err
	}

	return resp.Choices[0].Message.Content, prompt, nil
}

// Generate answer to the question, based on the description of the suspect.
// If Service defines non-empty URL, it is used as BaseURL for the OpenAI client - this allows usage of LLM proxies
// or other services compatible with OpenAI styled API.
// TODO: Add option to switch service (OpenAI, Anthropic, etc.)
func GenerateAnswer(question, description, model string, service Service) (string, error) {
	config := openai.DefaultConfig(service.Token)
	if service.URL.String != "" {
		config.BaseURL = service.URL.String
	}
	client := openai.NewClientWithConfig(config)
	const answerReflection = `ROLE: You are a player of Unusual Suspects board game - text based version. You are a witness.
TASK: Read the description of the perpetrator and the question the police officer asked you about perpetrator.
Write a short reflection on the perpetrator in relation to the question.
Try to think both ways, both about the positive answer and the negative one, which one you lean more towards. Cca 100 words.
QUESTION: %s
DESCRIPTION OF PERPETRATOR: %s`
	reflectionPrompt := fmt.Sprintf(answerReflection, question, description)
	reflectionResp, err := client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: model,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleUser,
					Content: reflectionPrompt,
				},
			},
		},
	)
	if err != nil {
		log.Printf("Error generating answer: %v\n", err)
		return "", err
	}
	reflection := reflectionResp.Choices[0].Message.Content
	log.Printf("AI sent reflection: %s\n", reflection)

	const answerBoolean = `ROLE: You are a senior decision maker.
TASK: Answer the question YES or NO. Do not write anything else. Do not write anything else. Just write YES, or NO based on the previous information.`
	decisionResp, err := client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: model,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleUser,
					Content: reflectionPrompt,
				},
				{
					Role:    openai.ChatMessageRoleAssistant,
					Content: reflection,
				},
				{
					Role:    openai.ChatMessageRoleUser,
					Content: answerBoolean,
				},
			},
		},
	)
	if err != nil {
		log.Printf("Error generating answer: %v\n", err)
		return "", err
	}
	decision := decisionResp.Choices[0].Message.Content
	log.Printf("AI sent decided: %s\n", reflection)
	return decision, nil
}
