// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FreeSuspect(arg1:string):Promise<boolean>;

export function GetAnswerFromAI():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function NewGame():Promise<void>;

export function NewRound():Promise<string>;
