// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function EliminateSuspect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActiveModel():Promise<database.Model>;

export function GetAllModels():Promise<Array<database.Model>>;

export function GetGame():Promise<database.Game>;

export function GetScores():Promise<Array<database.FinalScore>>;

export function GetServices():Promise<Array<database.Service>>;

export function NewGame():Promise<database.Game>;

export function NextInvestigation():Promise<database.Game>;

export function NextRound():Promise<database.Game>;

export function SaveScore(arg1:string,arg2:string):Promise<void>;

export function SaveToken(arg1:string,arg2:string):Promise<void>;

export function SetActiveModel(arg1:string):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function WaitForAnswer(arg1:string):Promise<string>;
