// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EliminateSuspect(arg1, arg2, arg3) {
  return window['go']['main']['App']['EliminateSuspect'](arg1, arg2, arg3);
}

export function GetActiveModel() {
  return window['go']['main']['App']['GetActiveModel']();
}

export function GetAllModels() {
  return window['go']['main']['App']['GetAllModels']();
}

export function GetGame() {
  return window['go']['main']['App']['GetGame']();
}

export function GetScores() {
  return window['go']['main']['App']['GetScores']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function NewGame() {
  return window['go']['main']['App']['NewGame']();
}

export function NextInvestigation() {
  return window['go']['main']['App']['NextInvestigation']();
}

export function NextRound() {
  return window['go']['main']['App']['NextRound']();
}

export function SaveScore(arg1, arg2) {
  return window['go']['main']['App']['SaveScore'](arg1, arg2);
}

export function SaveToken(arg1, arg2) {
  return window['go']['main']['App']['SaveToken'](arg1, arg2);
}

export function SetActiveModel(arg1) {
  return window['go']['main']['App']['SetActiveModel'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function WaitForAnswer(arg1) {
  return window['go']['main']['App']['WaitForAnswer'](arg1);
}
