// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FreeSuspect(arg1) {
  return window['go']['main']['App']['FreeSuspect'](arg1);
}

export function GetAnswerFromAI() {
  return window['go']['main']['App']['GetAnswerFromAI']();
}

export function GetGame() {
  return window['go']['main']['App']['GetGame']();
}

export function NewGame() {
  return window['go']['main']['App']['NewGame']();
}

export function NextLevel() {
  return window['go']['main']['App']['NextLevel']();
}
