// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EliminateSuspect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetGame():Promise<main.Game>;

export function GetScores():Promise<Array<main.FinalScore>>;

export function NewGame():Promise<main.Game>;

export function NextInvestigation():Promise<main.Game>;

export function NextRound():Promise<main.Game>;

export function SaveScore(arg1:string,arg2:string):Promise<void>;

export function WaitForAnswer(arg1:string):Promise<string>;
